// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package sdk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for RecordResultErrorCode.
const (
	RecordResultErrorCodeDUPLICATERECORD    RecordResultErrorCode = "DUPLICATE_RECORD"
	RecordResultErrorCodeRECORDNOTUPDATABLE RecordResultErrorCode = "RECORD_NOT_UPDATABLE"
	RecordResultErrorCodeSAVEFAILURE        RecordResultErrorCode = "SAVE_FAILURE"
	RecordResultErrorCodeUPDATEFAILURE      RecordResultErrorCode = "UPDATE_FAILURE"
)

// Defines values for UpdateRecordResultErrorCode.
const (
	UpdateRecordResultErrorCodeDUPLICATERECORD    UpdateRecordResultErrorCode = "DUPLICATE_RECORD"
	UpdateRecordResultErrorCodeRECORDNOTUPDATABLE UpdateRecordResultErrorCode = "RECORD_NOT_UPDATABLE"
	UpdateRecordResultErrorCodeSAVEFAILURE        UpdateRecordResultErrorCode = "SAVE_FAILURE"
	UpdateRecordResultErrorCodeUPDATEFAILURE      UpdateRecordResultErrorCode = "UPDATE_FAILURE"
)

// ConflictResponse defines model for ConflictResponse.
type ConflictResponse struct {
	DuplicateRecords *float32        `json:"duplicateRecords,omitempty"`
	Error            *string         `json:"error,omitempty"`
	Results          *[]RecordResult `json:"results,omitempty"`
	TotalRecords     *float32        `json:"totalRecords,omitempty"`
}

// Dimension defines model for Dimension.
type Dimension struct {
	// DryRun ドライラン実行フラグ（オプション）
	DryRun *bool `json:"dry_run,omitempty"`

	// Name ディメンション名
	Name string `json:"name"`

	// Quantity 使用量
	Quantity float32 `json:"quantity"`

	// UsageAllocations 使用量アロケーション（オプション）
	UsageAllocations *[]UsageAllocation `json:"usage_allocations,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error エラーメッセージ
	Error string `json:"error"`

	// RequestId リクエストID
	RequestId *string `json:"requestId,omitempty"`
}

// NotUpdatableResponse defines model for NotUpdatableResponse.
type NotUpdatableResponse struct {
	Error        *string               `json:"error,omitempty"`
	RequestId    *string               `json:"requestId,omitempty"`
	Results      *[]UpdateRecordResult `json:"results,omitempty"`
	TotalRecords *float32              `json:"totalRecords,omitempty"`
}

// PartialSuccessResponse defines model for PartialSuccessResponse.
type PartialSuccessResponse struct {
	DuplicateRecords  *float32        `json:"duplicateRecords,omitempty"`
	FailedRecords     *float32        `json:"failedRecords,omitempty"`
	Message           *string         `json:"message,omitempty"`
	Results           *[]RecordResult `json:"results,omitempty"`
	SuccessfulRecords *float32        `json:"successfulRecords,omitempty"`
	TotalRecords      *float32        `json:"totalRecords,omitempty"`
}

// PartialUpdateResponse defines model for PartialUpdateResponse.
type PartialUpdateResponse struct {
	FailedRecords     *float32              `json:"failedRecords,omitempty"`
	Message           *string               `json:"message,omitempty"`
	Results           *[]UpdateRecordResult `json:"results,omitempty"`
	SuccessfulRecords *float32              `json:"successfulRecords,omitempty"`
	TotalRecords      *float32              `json:"totalRecords,omitempty"`
}

// RecordResult defines model for RecordResult.
type RecordResult struct {
	// CustomerIdentifier 顧客識別子
	CustomerIdentifier *string `json:"customerIdentifier,omitempty"`

	// Error エラーメッセージ（失敗時）
	Error *string `json:"error,omitempty"`

	// ErrorCode エラーコード（失敗時）
	ErrorCode *RecordResultErrorCode `json:"errorCode,omitempty"`

	// HttpStatusCode HTTPステータスコード（失敗時）
	HttpStatusCode *float32 `json:"httpStatusCode,omitempty"`

	// RecordId レコードID（顧客識別子:タイムスタンプ）
	RecordId *string `json:"recordId,omitempty"`

	// RequestId リクエストID
	RequestId *string `json:"requestId,omitempty"`

	// Success レコード処理の成功/失敗
	Success *bool `json:"success,omitempty"`

	// Timestamp レコードのタイムスタンプ
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// RecordResultErrorCode エラーコード（失敗時）
type RecordResultErrorCode string

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Message      *string         `json:"message,omitempty"`
	Results      *[]RecordResult `json:"results,omitempty"`
	TotalRecords *float32        `json:"totalRecords,omitempty"`
}

// Tag defines model for Tag.
type Tag struct {
	// Key タグキー
	Key string `json:"key"`

	// Value タグ値
	Value string `json:"value"`
}

// UpdateRecordResult defines model for UpdateRecordResult.
type UpdateRecordResult struct {
	// CustomerIdentifier 顧客識別子
	CustomerIdentifier *string `json:"customerIdentifier,omitempty"`

	// Error エラーメッセージ（失敗時）
	Error *string `json:"error,omitempty"`

	// ErrorCode エラーコード（失敗時）
	ErrorCode *UpdateRecordResultErrorCode `json:"errorCode,omitempty"`

	// HttpStatusCode HTTPステータスコード（失敗時）
	HttpStatusCode *float32 `json:"httpStatusCode,omitempty"`

	// RecordId レコードID（顧客識別子:タイムスタンプ）
	RecordId *string `json:"recordId,omitempty"`

	// RequestId リクエストID
	RequestId *string `json:"requestId,omitempty"`

	// Success レコード処理の成功/失敗
	Success *bool `json:"success,omitempty"`

	// Timestamp レコードのタイムスタンプ
	Timestamp *float32 `json:"timestamp,omitempty"`

	// UpdatedFields 更新されたフィールド一覧
	UpdatedFields *[]string `json:"updatedFields,omitempty"`
}

// UpdateRecordResultErrorCode エラーコード（失敗時）
type UpdateRecordResultErrorCode string

// UpdateSuccessResponse defines model for UpdateSuccessResponse.
type UpdateSuccessResponse struct {
	Message      *string               `json:"message,omitempty"`
	Results      *[]UpdateRecordResult `json:"results,omitempty"`
	TotalRecords *float32              `json:"totalRecords,omitempty"`
}

// UsageAllocation defines model for UsageAllocation.
type UsageAllocation struct {
	// AllocatedUsageQuantity 割り当て使用量
	AllocatedUsageQuantity *float32 `json:"allocated_usage_quantity,omitempty"`

	// Tags アロケーションに関連するタグ
	Tags *[]Tag `json:"tags,omitempty"`
}

// UsageRecord defines model for UsageRecord.
type UsageRecord struct {
	// CustomerIdentifier 顧客識別子
	CustomerIdentifier string    `json:"CustomerIdentifier"`
	Dimension          Dimension `json:"dimension"`

	// ProductId AWS Marketplace製品ID
	ProductId string `json:"product_id"`

	// StartTime 使用量レコードの開始時刻（ISO 8601形式）
	StartTime time.Time `json:"start_time"`
}

// CreateUsageRecordsJSONBody defines parameters for CreateUsageRecords.
type CreateUsageRecordsJSONBody = []UsageRecord

// UpdateUsageRecordsJSONBody defines parameters for UpdateUsageRecords.
type UpdateUsageRecordsJSONBody = []UsageRecord

// CreateUsageRecordsJSONRequestBody defines body for CreateUsageRecords for application/json ContentType.
type CreateUsageRecordsJSONRequestBody = CreateUsageRecordsJSONBody

// UpdateUsageRecordsJSONRequestBody defines body for UpdateUsageRecords for application/json ContentType.
type UpdateUsageRecordsJSONRequestBody = UpdateUsageRecordsJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// OptionsUsageRecords request
	OptionsUsageRecords(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUsageRecordsWithBody request with any body
	CreateUsageRecordsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUsageRecords(ctx context.Context, body CreateUsageRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateUsageRecordsWithBody request with any body
	UpdateUsageRecordsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateUsageRecords(ctx context.Context, body UpdateUsageRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) OptionsUsageRecords(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOptionsUsageRecordsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUsageRecordsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUsageRecordsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUsageRecords(ctx context.Context, body CreateUsageRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUsageRecordsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateUsageRecordsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUsageRecordsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateUsageRecords(ctx context.Context, body UpdateUsageRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUsageRecordsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewOptionsUsageRecordsRequest generates requests for OptionsUsageRecords
func NewOptionsUsageRecordsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/usage-records")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("OPTIONS", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateUsageRecordsRequest calls the generic CreateUsageRecords builder with application/json body
func NewCreateUsageRecordsRequest(server string, body CreateUsageRecordsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUsageRecordsRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateUsageRecordsRequestWithBody generates requests for CreateUsageRecords with any type of body
func NewCreateUsageRecordsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/usage-records")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateUsageRecordsRequest calls the generic UpdateUsageRecords builder with application/json body
func NewUpdateUsageRecordsRequest(server string, body UpdateUsageRecordsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateUsageRecordsRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateUsageRecordsRequestWithBody generates requests for UpdateUsageRecords with any type of body
func NewUpdateUsageRecordsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/usage-records")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// OptionsUsageRecordsWithResponse request
	OptionsUsageRecordsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OptionsUsageRecordsResponse, error)

	// CreateUsageRecordsWithBodyWithResponse request with any body
	CreateUsageRecordsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUsageRecordsResponse, error)

	CreateUsageRecordsWithResponse(ctx context.Context, body CreateUsageRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUsageRecordsResponse, error)

	// UpdateUsageRecordsWithBodyWithResponse request with any body
	UpdateUsageRecordsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUsageRecordsResponse, error)

	UpdateUsageRecordsWithResponse(ctx context.Context, body UpdateUsageRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUsageRecordsResponse, error)
}

type OptionsUsageRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r OptionsUsageRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OptionsUsageRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUsageRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SuccessResponse
	JSON207      *PartialSuccessResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON409      *ConflictResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateUsageRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUsageRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateUsageRecordsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UpdateSuccessResponse
	JSON207      *PartialUpdateResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON409      *NotUpdatableResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateUsageRecordsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateUsageRecordsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// OptionsUsageRecordsWithResponse request returning *OptionsUsageRecordsResponse
func (c *ClientWithResponses) OptionsUsageRecordsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OptionsUsageRecordsResponse, error) {
	rsp, err := c.OptionsUsageRecords(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOptionsUsageRecordsResponse(rsp)
}

// CreateUsageRecordsWithBodyWithResponse request with arbitrary body returning *CreateUsageRecordsResponse
func (c *ClientWithResponses) CreateUsageRecordsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUsageRecordsResponse, error) {
	rsp, err := c.CreateUsageRecordsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUsageRecordsResponse(rsp)
}

func (c *ClientWithResponses) CreateUsageRecordsWithResponse(ctx context.Context, body CreateUsageRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUsageRecordsResponse, error) {
	rsp, err := c.CreateUsageRecords(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUsageRecordsResponse(rsp)
}

// UpdateUsageRecordsWithBodyWithResponse request with arbitrary body returning *UpdateUsageRecordsResponse
func (c *ClientWithResponses) UpdateUsageRecordsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUsageRecordsResponse, error) {
	rsp, err := c.UpdateUsageRecordsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUsageRecordsResponse(rsp)
}

func (c *ClientWithResponses) UpdateUsageRecordsWithResponse(ctx context.Context, body UpdateUsageRecordsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUsageRecordsResponse, error) {
	rsp, err := c.UpdateUsageRecords(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUsageRecordsResponse(rsp)
}

// ParseOptionsUsageRecordsResponse parses an HTTP response from a OptionsUsageRecordsWithResponse call
func ParseOptionsUsageRecordsResponse(rsp *http.Response) (*OptionsUsageRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OptionsUsageRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseCreateUsageRecordsResponse parses an HTTP response from a CreateUsageRecordsWithResponse call
func ParseCreateUsageRecordsResponse(rsp *http.Response) (*CreateUsageRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUsageRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 207:
		var dest PartialSuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON207 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateUsageRecordsResponse parses an HTTP response from a UpdateUsageRecordsWithResponse call
func ParseUpdateUsageRecordsResponse(rsp *http.Response) (*UpdateUsageRecordsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateUsageRecordsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UpdateSuccessResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 207:
		var dest PartialUpdateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON207 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest NotUpdatableResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
